// constants/profileData.js
export const PROFILE_DATA = {
  hair_colors: [
    { id: 1, name: "Black" },
    { id: 2, name: "Brown" },
    { id: 3, name: "Blonde" },
    { id: 4, name: "Red" },
    { id: 5, name: "Gray" },
    { id: 6, name: "Other" },
  ],
  heights: [
    { id: 1, name: "150 cm" },
    { id: 2, name: "160 cm" },
    { id: 3, name: "170 cm" },
    { id: 4, name: "180 cm" },
    { id: 5, name: "190 cm" },
  ],
  weights: [
    { id: 1, name: "50 kg" },
    { id: 2, name: "60 kg" },
    { id: 3, name: "70 kg" },
    { id: 4, name: "80 kg" },
    { id: 5, name: "90 kg" },
  ],
  origins: [
    { id: 1, name: "Middle Eastern" },
    { id: 2, name: "African" },
  ],
  marital_statuses: [
    { id: 1, name: "Single" },
    { id: 2, name: "Married" },
    { id: 3, name: "Divorced" },
    { id: 4, name: "Widowed" },
  ],
  skin_colors: [
    { id: 1, name: "Fair" },
    { id: 2, name: "Medium" },
    { id: 3, name: "Dark" },
    { id: 4, name: "Other" },
  ],
  zodiac_signs: [
    { id: 1, name: "Aries" },
    { id: 2, name: "Taurus" },
    { id: 3, name: "Gemini" },
    { id: 4, name: "Cancer" },
    { id: 5, name: "Leo" },
    { id: 6, name: "Virgo" },
    { id: 7, name: "Libra" },
    { id: 8, name: "Scorpio" },
    { id: 9, name: "Sagittarius" },
    { id: 10, name: "Capricorn" },
    { id: 11, name: "Aquarius" },
    { id: 12, name: "Pisces" },
  ],
  hobbies: [
    { id: 1, name: "Photography" },
    { id: 2, name: "Gardening" },
    { id: 3, name: "Painting" },
    { id: 4, name: "Cycling" },
    { id: 5, name: "Hiking" },
  ],
  pets: [
    { id: 1, name: "Cat" },
    { id: 2, name: "Dog" },
    { id: 3, name: "Bird" },
    { id: 4, name: "Fish" },
    { id: 5, name: "Other" },
  ],
  sports_activities: [
    { id: 1, name: "Football" },
    { id: 2, name: "Swimming" },
    { id: 3, name: "Basketball" },
    { id: 4, name: "Tennis" },
    { id: 5, name: "Running" },
    { id: 6, name: "Other" },
  ],
  smoking_tools: [
    { id: 1, name: "Cigarettes" },
    { id: 2, name: "Shisha" },
    { id: 3, name: "E-cigarettes" },
    { id: 4, name: "Other" },
  ],
  drinking_statuses: [
    { id: 1, name: "Drinks Alcohol" },
    { id: 2, name: "Does not drink Alcohol" },
    { id: 3, name: "Occasionally drinks Alcohol" },
    { id: 4, name: "Prefers not to say" },
  ],
  specializations: [
    { id: 1, name: "Computer Science" },
    { id: 2, name: "Engineering" },
    { id: 3, name: "Business Administration" },
    { id: 4, name: "Medicine" },
  ],
  position_levels: [
    { id: 1, name: "Entry Level" },
    { id: 2, name: "Mid Level" },
    { id: 3, name: "Senior Level" },
    { id: 4, name: "Manager" },
  ],
  educational_levels: [
    { id: 1, name: "High School" },
    { id: 2, name: "Bachelor's Degree" },
    { id: 3, name: "Master's Degree" },
    { id: 4, name: "PhD" },
  ],
  countries: [
    { id: 1, name: "Jordan" },
    { id: 2, name: "Egypt" },
    { id: 3, name: "Lebanon" },
    { id: 4, name: "Syria" },
    { id: 5, name: "Palestine" },
  ],
  religions: [
    { id: 1, name: "Islam" },
    { id: 2, name: "Christianity" },
  ],
  nationalities: [
    { id: 1, name: "Jordanian" },
    { id: 2, name: "Egyptian" },
    { id: 3, name: "Lebanese" },
    { id: 4, name: "Syrian" },
    { id: 5, name: "Palestinian" },
  ],
  housing_statuses: [
    { id: 1, name: "Owned" },
    { id: 2, name: "Rented" },
    { id: 3, name: "Living with Parents" },
    { id: 4, name: "Other" },
  ],
  financial_statuses: [
    { id: 1, name: "Stable" },
    { id: 2, name: "Needs Improvement" },
    { id: 3, name: "Excellent" },
    { id: 4, name: "Poor" },
  ],
};
